---- =============================================
---- Create database template
---- =============================================
USE master
GO

-- Drop the database if it already exists
IF  EXISTS (
	SELECT name 
		FROM sys.databases 
		WHERE name = N'<WHOLESALE_STORE>'
)
DROP DATABASE WHOLESALE_STORE
GO

CREATE DATABASE WHOLESALE_STORE
GO

 --=========================================
 ----Create table template
 --=========================================
USE WHOLESALE_STORE
GO

IF OBJECT_ID('dbo.PRODUCT', 'U') IS NOT NULL
  DROP TABLE dbo.PRODUCT
GO

CREATE TABLE dbo.PRODUCT
(
	ID int IDENTITY NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	BARCODE VARCHAR(50) NULL,
	AMOUNT float(2) NOT NULL,
	PRICE decimal(18,2) NOT NULL,
	CATEGORY_ID int NOT  NULL,
	UNIT_ID int NOT  NULL,
	CONSTRAINT PK_PRODUCT_table PRIMARY KEY (ID),
	CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID),
	CONSTRAINT FK_PRODUCT_UNIT FOREIGN KEY (UNIT_ID) REFERENCES UNIT(ID)
)
GO

IF OBJECT_ID('dbo.CATEGORY', 'U') IS NOT NULL
  DROP TABLE dbo.CATEGORY
GO

CREATE TABLE dbo.CATEGORY
(
	ID int IDENTITY NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	CONSTRAINT PK_CATEGORY_table PRIMARY KEY (ID)
)
GO

IF OBJECT_ID('dbo.CUSTOMER', 'U') IS NOT NULL
  DROP TABLE dbo.CUSTOMER
GO

CREATE TABLE dbo.CUSTOMER
(
	ID int IDENTITY NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	C_ADDRESS VARCHAR(50) NOT NULL,
	PHONE_NUMBER VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	CONSTRAINT PK_CUSTOMER_table PRIMARY KEY (ID)
)
GO

IF OBJECT_ID('dbo.ORDER', 'U') IS NOT NULL
  DROP TABLE dbo.[ORDER]
GO

CREATE TABLE dbo.[ORDER]
(
	ID int IDENTITY NOT NULL,
	ORDERNUMBER VARCHAR(50) NOT NULL,
	[DATE] datetime NOT NULL,
	TOTALSUM decimal(18,2) NULL,
	CUSTOMER_ID int NOT NULL,
	[USER_ID] int NOT NULL,
	CONSTRAINT PK_ORDER_table PRIMARY KEY (ID),
	CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID),	
	CONSTRAINT FK_ORDER_USER FOREIGN KEY ([USER_ID]) REFERENCES [USER](ID)
)
GO


IF OBJECT_ID('dbo.ORDER_ITEM', 'U') IS NOT NULL
  DROP TABLE dbo.ORDER_ITEM
GO

CREATE TABLE dbo.ORDER_ITEM
(
	ID int IDENTITY NOT NULL,
	ORDER_ID int NOT NULL,
	PRODUCT_ID int NOT NULL,
	AMOUNT float(2) NOT NULL,
	PRICE decimal(18,2) NOT NULL,
	CONSTRAINT PK_ORDER_ITEM_table PRIMARY KEY (ID),
	CONSTRAINT FK_ORDER_ITEM_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID),
	CONSTRAINT FK_ORDER_ITEM_ORDER FOREIGN KEY (ORDER_ID) REFERENCES [ORDER](ID)
)
GO


IF OBJECT_ID('dbo.USERTYPE', 'U') IS NOT NULL
  DROP TABLE dbo.USERTYPE
GO

CREATE TABLE dbo.USERTYPE
(
	ID int IDENTITY NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	CONSTRAINT PK_USERTYPE_table PRIMARY KEY (ID)
)
GO


IF OBJECT_ID('dbo.USER', 'U') IS NOT NULL
  DROP TABLE dbo.[USER]
GO

CREATE TABLE dbo.[USER]
(
	ID int IDENTITY NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	[PASSWORD] VARCHAR(50) NOT NULL,
	USERTYPE_ID INT NOT NULL,
	CONSTRAINT PK_USER_table PRIMARY KEY (ID),
	CONSTRAINT FK_USER_USERTYPE FOREIGN KEY (USERTYPE_ID) REFERENCES USERTYPE(ID)
)
GO

IF OBJECT_ID('dbo.UNIT', 'U') IS NOT NULL
  DROP TABLE dbo.UNIT
GO

CREATE TABLE dbo.UNIT
(
	ID int IDENTITY NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	CONSTRAINT PK_UNIT_table PRIMARY KEY (ID)
)
GO

CREATE TABLE dbo.LOGGEDUSER
(
	ID int IDENTITY NOT NULL,
	VALUE INT NULL,
	CONSTRAINT PK_LOGGEDUSER_table PRIMARY KEY (ID)
)
GO








