//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WholesaleStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public ORDER()
        {
            this.ORDER_ITEM = new HashSet<ORDER_ITEM>();
        }
    
        public int ID { get; set; }
        public string ORDERNUMBER { get; set; }
        public System.DateTime DATE { get; set; }
        public Nullable<decimal> TOTALSUM { get; set; }
        public int CUSTOMER_ID { get; set; }
        public int USER_ID { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual ICollection<ORDER_ITEM> ORDER_ITEM { get; set; }
        public virtual USER USER { get; set; }
    }
}
