//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WholesaleStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public PRODUCT()
        {
            this.ORDER_ITEM = new HashSet<ORDER_ITEM>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string BARCODE { get; set; }
        public float AMOUNT { get; set; }
        public decimal PRICE { get; set; }
        public int CATEGORY_ID { get; set; }
        public int UNIT_ID { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual ICollection<ORDER_ITEM> ORDER_ITEM { get; set; }
        public virtual UNIT UNIT { get; set; }
    }
}
