//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WholesaleStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WHOLESALE_STOREEntities : DbContext
    {
        public WHOLESALE_STOREEntities()
            : base("name=WHOLESALE_STOREEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CATEGORY> CATEGORY { get; set; }
        public DbSet<CUSTOMER> CUSTOMER { get; set; }
        public DbSet<LOGGEDUSER> LOGGEDUSER { get; set; }
        public DbSet<ORDER> ORDER { get; set; }
        public DbSet<ORDER_ITEM> ORDER_ITEM { get; set; }
        public DbSet<PRODUCT> PRODUCT { get; set; }
        public DbSet<UNIT> UNIT { get; set; }
        public DbSet<USER> USER { get; set; }
        public DbSet<USERTYPE> USERTYPE { get; set; }
    }
}
